### ISSUE TITLE
'delete' entries don't leave blank spaces anymore

### ISSUE THREAD

**Issue by CultusMechanicus** [olicooper/esphome-nspanel-lovelace-native#11]
Ok, both my panels are now running this, AppDaemon is gone (wohoo). While cardThermo gets support, I've been using 'delete' to leave a blank space for the heating in my menu. It was working, but with the recent changes it leaves a '?' in a circle.

**Comment by olicooper** [comment]
Yeah this is due to recent changes to how I store and render entity states. The refactor needed to happen to fix a problem with having the same entity on multiple pages but the result of that was that (at least for now) 'delete' entities are rendered like normal entities. I will need to figure out the best approach to fix it but it is on my to do list 🙂

**Comment by CultusMechanicus** [comment]
Btw, sorry for raising a million tickets, but this is a really nice project. It's hugely simplified my setup, and made the panels much snappier.
